remote_theme: just-the-docs/just-the-docs

title: Inventory Management UI
description: A modern Vue.js 3 application for inventory management

url: https://metanull.github.io
baseurl: /inventory-management-ui

# Logo and favicon
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Color scheme
color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/metanull/inventory-management-ui
  - title: API Documentation
    url: https://metanull.github.io/inventory-app

# Footer
footer_content: "Copyright &copy; 2025 Pascal Havelange. Made with ❤️ using 💎 Ruby and 🐍 Python."

# Back to top
back_to_top: true
back_to_top_text: "Back to top"

# Last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# GitHub
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/metanull/inventory-management-ui"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Collections for blog posts and commit documentation
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  docs:
    output: true
    permalink: /commits/:name/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - COMMIT_DOCS_README.md
  - generate-commit-docs.py
  - generate-commit-docs.ps1
  - commit-docs.log
  - contributing-new.md

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass
sass:
  style: compressed

# Custom CSS
aux_links:
  "View on GitHub":
    - "https://github.com/metanull/inventory-management-ui"
