name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run linting
      run: npm run lint:check
    
    - name: Run formatting check
      run: npm run format:check
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Check test coverage threshold
      run: |
        npm run test:coverage -- --reporter=json --outputFile=coverage.json
        node -e "
          const coverage = require('./coverage.json');
          const threshold = 80;
          const actual = coverage.total.lines.pct;
          if (actual < threshold) {
            console.error(\`Coverage \${actual}% is below threshold \${threshold}%\`);
            process.exit(1);
          }
          console.log(\`Coverage \${actual}% meets threshold \${threshold}%\`);
        "
    
    - name: Build application
      run: npm run build
    
    - name: Comment PR with build status
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Build completed successfully! All checks passed.'
          })

  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
